name: simasu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  provider: ^6.0.0
  http: ^1.6.0
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/simasu_mark.png
    - assets/images/profile_default.png
    - assets/images/profile_alt.png